
server:
  port: 8880
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3336/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    format-sql: true
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 863120457057-4pdleg0kotvineosk0go4medse798hrk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 275764574541184
            client-secret: 5736962d7dad3a50417a9a7eaf19764a
            scope:
              - email
              - public_profile

          naver:
            client-id: Aihfl95ECD301WFj0bda
            client-secret: 5YXPYt7EsR
            scope:
              - name
              - email
            client-name: Naver #대문자로 시작함
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8880/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 네이버에서 response를 key 값으로 보내줌